routes/web.php
<?php

// 用户默认的用户注册登录路由
Auth::routes();
Route::get('/home', 'Home\HomeController@index')->name('home');

Route::domain(env('DOMAIN_PC'))->group(function() {
	// 管理员后台登录
	Route::prefix('admin')->group(function() {
		Route::get('login', 'Admin\LoginController@login')->name('admin.login');
		Route::post('login', 'Admin\LoginController@doLogin')->name('admin.dologin');
		Route::get('logout', 'Admin\LoginController@logout')->name('admin.logout');
		Route::get('dashboard', 'Admin\DashboardController@dashboard')->name('admin.dashboard');
		Route::get('changepassword', 'Admin\UserController@changePassword')->name('admin.changePassword');
		Route::post('changepassword', 'Admin\UserController@doChangePassword')->name('admin.doChangePassword');
		Route::resource('goodsCategorys', 'Admin\GoodsCategoryController');
		Route::get('couponRules/{id}', 'Admin\CouponRulesController@show')->name('admin.couponRule.show');
		Route::get('couponRules/{id}/edit', 'Admin\CouponRulesController@edit')->name('admin.couponRule.edit');
		Route::post('couponRules/', 'Admin\CouponRulesController@store')->name('admin.couponRule.store');
		Route::get('couponRules/{id}/create', 'Admin\CouponRulesController@create')->name('admin.couponRule.create');
		Route::post('couponRules/{id}/update', 'Admin\CouponRulesController@update')->name('admin.couponRule.update');
	});

	// PC端的页面
	Route::get('/', 'Index\PC\IndexController@index')->name('pc.index');
	Route::get('/{id}{sort?}', 'Index\PC\IndexController@categoryOne')->name('pc.goodsCategorys.categoryOne')->where('id', '[0-9]+');
	Route::get('/sub{id}{sort?}', 'Index\PC\IndexController@categoryTwo')->name('pc.goodsCategorys.categoryTwo')->where('id', '[0-9]+');
	Route::get('/son{id}{sort?}', 'Index\PC\IndexController@categorySon')->name('pc.goodsCategorys.categorySon')->where('id', '[0-9]+');
	Route::get('/agc', 'Index\PC\AllGoodsCategoryController@index')->name('pc.allGoodsCategory.index');
	Route::get('/search', 'Index\PC\SearchController@index')->name('pc.search.index');
	Route::get('/search/all/', 'Index\PC\SearchController@all')->name('pc.search.all');
	Route::get('/search/tmall/', 'Index\PC\SearchController@tmall')->name('pc.search.tmall');
	Route::get('/search/ju/', 'Index\PC\SearchController@ju')->name('pc.search.ju');
	Route::get('/search/tpwd/', 'Index\PC\SearchController@tpwd')->name('pc.search.tpwd');
	Route::get('/taoqianggou', 'Index\PC\TaoQiangGouController@index')->name('pc.taoqianggou.index');
	Route::get('/iteminfo/{id?}', 'Index\PC\ItemInfoController@iteminfo')->name('pc.itemInfo.iteminfo')->where('id', '[0-9]+');
	Route::get('/pintuaninfo/{id?}', 'Index\PC\ItemInfoController@pinTuanInfo')->name('pc.itemInfo.pinTuanInfo')->where('id', '[0-9]+');
	Route::get('/zhibo-{id?}', 'Index\PC\OptimusMaterialController@zhibo')->name('pc.optimusMaterial.zhibo')->where('id', '[0-9]+');
	Route::get('/brand-{id?}', 'Index\PC\OptimusMaterialController@brand')->name('pc.optimusMaterial.brand')->where('id', '[0-9]+');
	Route::get('/baby-{id?}', 'Index\PC\OptimusMaterialController@baby')->name('pc.optimusMaterial.baby')->where('id', '[0-9]+');
	Route::get('/pintuan', 'Index\PC\OptimusMaterialController@pintuan')->name('pc.optimusMaterial.pintuan');
	Route::get('/sales', 'Index\PC\OptimusMaterialController@sales')->name('pc.optimusMaterial.sales');
	Route::get('/fashion', 'Index\PC\OptimusMaterialController@fashion')->name('pc.optimusMaterial.fashion');
	Route::get('/recommend', 'Index\PC\OptimusMaterialController@recommend')->name('pc.optimusMaterial.recommend');
	Route::get('/pintuan', 'Index\PC\OptimusMaterialController@pintuan')->name('pc.optimusMaterial.pintuan');
	Route::get('/download/app', 'Index\Share\DownloadController@appPC')->name('pc.download.app');

	Route::prefix('api/alimama')->group(function() {
		Route::post('taobaoTbkDgItemCouponGet', 'Api\AlimamaController@taobaoTbkDgItemCouponGet')->name('pc.api.alimama.taobaoTbkDgItemCouponGet');
		Route::post('taobaoTbkDgMaterialOptional', 'Api\AlimamaController@taobaoTbkDgMaterialOptional')->name('pc.api.alimama.taobaoTbkDgMaterialOptional');
		Route::post('taobaoJuItemsSearch', 'Api\AlimamaController@taobaoJuItemsSearch')->name('pc.api.alimama.taobaoJuItemsSearch');
		Route::post('taobaoTbkJuTqgGet', 'Api\AlimamaController@taobaoTbkJuTqgGet')->name('pc.api.alimama.taobaoTbkJuTqgGet');
		Route::post('taobaoTbkDgOptimusMaterial', 'Api\AlimamaController@taobaoTbkDgOptimusMaterial')->name('pc.api.alimama.taobaoTbkDgOptimusMaterial');
	});
	Route::prefix('api/item')->group(function() {
		Route::post('itemimages/{id?}', 'Api\ItemInfoImagesController@itemDetailImage')->name('pc.api.itemInfoImages.itemDetailImage')->where('id', '[0-9]+');
	});
});

Route::domain(env('DOMAIN_WX'))->group(function() {
	Route::get('/', 'Index\WX\IndexController@index')->name('wx.index');
	Route::get('/{id}{sort?}', 'Index\WX\IndexController@categoryOne')->name('goodsCategorys.categoryOne')->where('id', '[0-9]+');
	Route::get('/sub{id}{sort?}', 'Index\WX\IndexController@categoryTwo')->name('goodsCategorys.categoryTwo')->where('id', '[0-9]+');
	Route::get('/son{id}{sort?}', 'Index\WX\IndexController@categorySon')->name('goodsCategorys.categorySon')->where('id', '[0-9]+');
	Route::get('/agc', 'Index\WX\AllGoodsCategoryController@index')->name('wx.allGoodsCategory.index');
	Route::get('/search', 'Index\WX\SearchController@index')->name('wx.search.index');
	Route::get('/search/all/', 'Index\WX\SearchController@all')->name('wx.search.all');
	Route::get('/search/tmall/', 'Index\WX\SearchController@tmall')->name('wx.search.tmall');
	Route::get('/search/ju/', 'Index\WX\SearchController@ju')->name('wx.search.ju');
	Route::get('/search/tpwd/', 'Index\WX\SearchController@tpwd')->name('wx.search.tpwd');
	Route::get('/taoqianggou', 'Index\WX\TaoQiangGouController@index')->name('wx.taoqianggou.index');
	Route::get('/item/{id?}', 'Index\WX\ItemInfoController@item')->name('wx.itemInfo.item')->where('id', '[0-9]+');
	Route::get('/iteminfo/{id?}', 'Index\WX\ItemInfoController@iteminfo')->name('wx.itemInfo.iteminfo')->where('id', '[0-9]+');
	Route::get('/pintuaninfo/{id?}', 'Index\WX\ItemInfoController@pinTuanInfo')->name('wx.itemInfo.pinTuanInfo')->where('id', '[0-9]+');
	// Route::get('/couponInfo/{id?}', 'Index\WX\ItemInfoController@couponIndex')->name('wx.itemInfo.index.coupon')->where('id', '[0-9]+');
	// Route::get('/itemInfo/{id?}', 'Index\WX\ItemInfoController@itemIndex')->name('wx.itemInfo.index.material')->where('id', '[0-9]+');
	Route::get('/couponaction/{id}', 'Index\WX\CouponActionController@index')->name('wx.CouponAction.index')->where('id', '[0-9]+');
	Route::get('/pintuanaction/{id}', 'Index\WX\CouponActionController@pintuan')->name('wx.CouponAction.pintuan')->where('id', '[0-9]+');
	Route::get('/shareitem/{id}', 'Index\WX\ShareItemController@coupon')->name('wx.ShareItem.coupon')->where('id', '[0-9]+');
	Route::get('/sharepintuan/{id}', 'Index\WX\ShareItemController@pintuan')->name('wx.ShareItem.pintuan')->where('id', '[0-9]+');
	Route::get('/coupon/image/{id}', 'Index\WX\ImageController@couponShareImage')->name('wx.image.couponShareImage')->where('id', '[0-9]+');
	Route::get('/pintuan/image/{id}', 'Index\WX\ImageController@pintuanShareImage')->name('wx.image.pintuanShareImage')->where('id', '[0-9]+');
	Route::get('/url/der/tqg', 'Index\WX\WebJumpController@tqg')->name('wx.webJump.tqg');
	Route::get('/url/der/tqg/e/', 'Index\WX\WebJumpController@tqgForJs')->name('wx.webJump.tqgForJs');
	Route::get('/url/der/ju', 'Index\WX\WebJumpController@ju')->name('wx.webJump.ju');
	Route::get('/url/der/ju/js', 'Index\WX\WebJumpController@juForJs')->name('wx.webJump.juForJs');
	Route::get('/url/der/t/{tpwd}', 'Index\WX\WebJumpController@tpwd')->name('wx.webJump.tpwd');
	Route::get('/zhibo-{id}', 'Index\WX\OptimusMaterialController@zhibo')->name('wx.optimusMaterial.zhibo')->where('id', '[0-9]+');
	Route::get('/brand-{id}', 'Index\WX\OptimusMaterialController@brand')->name('wx.optimusMaterial.brand')->where('id', '[0-9]+');
	Route::get('/baby-{id}', 'Index\WX\OptimusMaterialController@baby')->name('wx.optimusMaterial.baby')->where('id', '[0-9]+');
	Route::get('/pintuan', 'Index\WX\OptimusMaterialController@pintuan')->name('wx.optimusMaterial.pintuan');
	Route::get('/sales', 'Index\WX\OptimusMaterialController@sales')->name('wx.optimusMaterial.sales');
	Route::get('/fashion', 'Index\WX\OptimusMaterialController@fashion')->name('wx.optimusMaterial.fashion');
	Route::get('/recommend', 'Index\WX\OptimusMaterialController@recommend')->name('wx.optimusMaterial.recommend');
	Route::get('/download/app', 'Index\Share\DownloadController@app')->name('wx.download.app');

	Route::prefix('api/alimama')->group(function() {
		Route::post('taobaoTbkDgItemCouponGet', 'Api\AlimamaController@taobaoTbkDgItemCouponGet')->name('api.alimama.taobaoTbkDgItemCouponGet');
		Route::post('taobaoTbkDgMaterialOptional', 'Api\AlimamaController@taobaoTbkDgMaterialOptional')->name('api.alimama.taobaoTbkDgMaterialOptional');
		Route::post('taobaoJuItemsSearch', 'Api\AlimamaController@taobaoJuItemsSearch')->name('api.alimama.taobaoJuItemsSearch');
		Route::post('taobaoTbkJuTqgGet', 'Api\AlimamaController@taobaoTbkJuTqgGet')->name('api.alimama.taobaoTbkJuTqgGet');
		Route::post('taobaoTbkDgOptimusMaterial', 'Api\AlimamaController@taobaoTbkDgOptimusMaterial')->name('api.alimama.taobaoTbkDgOptimusMaterial');
	});
	Route::prefix('api/item')->group(function() {
		Route::post('itemimages/{id?}', 'Api\ItemInfoImagesController@itemDetailImage')->name('api.itemInfoImages.itemDetailImage')->where('id', '[0-9]+');
	});
});

app/Models/GoodsCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GoodsCategory extends Model
{
  protected $table = "goods_categorys";

  protected $fillable = [
    'name', 'parent_id', 'path', 'order', 'is_shown', 'is_recommended', 'font_icon', 'image'
  ];

  protected $hidden = [
  ];

  // 与优惠券规则建立一对一关系
  public function couponRule()
  {
    return $this->hasOne('App\Models\TaobaoTbkDgMaterialOptional', 'goods_category_id');
  }

  // 与通用搜索规则建立一对一关系
  public function dgMaterialOptionalRule()
  {
    return $this->hasOne('App\Models\TaobaoTbkDgMaterialOptional', 'goods_category_id');
  }
}

app/Http/Controllers/Admin/GoodsCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\GoodsCategoryService;
use Auth;

class GoodsCategoryController extends Controller
{
    protected $goodsCategory;
    protected $pageSize = 50;

    public function __construct(GoodsCategoryService $goodsCategory)
    {
      $this->middleware('auth');
      $this->goodsCategory = $goodsCategory;
    }

    public function index()
    {
      $this->isAdmin();
      $title = '商品分类列表';
      $goodsCategories = $this->goodsCategory->get($this->pageSize);
      $couponRules = $this->goodsCategory->manyCouponRules($goodsCategories);

      return view('admin.goodsCategory.index', compact('title', 'goodsCategories', 'couponRules'));
    }

    public function show($id)
    {
      $this->isAdmin();
      $title = '商品分类信息详情';
      $goodsCategory = $this->goodsCategory->find($id);

      if (!$goodsCategory) {
        return redirect()->route('goodsCategorys.index')->with('warning', '要查看的信息不存在');
      }

      return view('admin.goodsCategory.show', compact('goodsCategory', 'title'));
    }

    public function create()
    {
      $this->isAdmin();

      $title = '增加栏目分类';
      $options = $this->goodsCategory->optionsForSelect();

      return view('admin.goodsCategory.create', compact('title', 'options'));
    }

    public function store(Request $request)
    {
      $this->validate($request, [
        'name' => 'required|min:1|max:30',
        'parent_id' => 'required|min:1',
        'order' => 'required|min:0|max:99',
        'is_shown' => 'required|boolean',
        'is_recommended' => 'required|boolean',
        'font_icon' => 'nullable|min:6|max:250',
        'image' => 'required|image',
      ]);

      $this->isAdmin();

      if ($this->goodsCategory->store($request)) {
        return back()->with('success', '成功增加栏目分类！');
      } else {
        return back()->with('warning', '增加栏目分类失败！');
      }
    }

    public function edit($id)
    {
      $this->isAdmin();
      $title = '修改商品分类信息';
      $goodsCategory = $this->goodsCategory->find($id);

      if (!$goodsCategory) {
        return redirect()->route('goodsCategorys.index')->with('warning', '准备删除的信息不存在');
      }

      $options = $this->goodsCategory->optionsForSelect();

      return view('admin.goodsCategory.edit', compact('title', 'goodsCategory', 'options'));
    }

    public function update($id, Request $request)
    {
      $this->isAdmin();

      $this->validate($request, [
        'name' => 'required|min:1|max:30',
        'parent_id' => 'required|min:1',
        'order' => 'required|min:0|max:99',
        'is_shown' => 'required|boolean',
        'is_recommended' => 'required|boolean',
        'font_icon' => 'nullable|min:6|max:250',
        'image' => 'nullable|image',
      ]);

      $result = $this->goodsCategory->updateById($id, $request);

      if (!$result) {
        return redirect()->route('goodsCategorys.index')->with('warning', '更新信息失败，请重新操作！');
      }

      return back()->with('info', '更新信息成功！');
    }

    public function destroy(Request $request)
    {
      $this->isAdmin();

      if (empty($request->goods_category_id)) {
        return redirect()->route('goodsCategorys.index')->with('warning', '删除信息失败，请重新操作！');
      }

      $result = $this->goodsCategory->destroyById($request->goods_category_id);

      if (!$result) {
        return back();
      }

      return back()->with('success', '成功删除id为'.$request->goods_category_id.'的商品分类信息！');
    }

    // 判断是否是管理员
    public function isAdmin()
    {
      $this->authorize('isAdmin', Auth::user());
    }
}

resources/views/admin/goodsCategory/_info.blade.php
@inject('show', 'App\Presenters\GoodsCategoryPresenter')
@inject('showCouponRule', 'App\Presenters\CouponRulePresenter')
@foreach($goodsCategories as $goodsCategory)
<tr>
    <td>{{ $goodsCategory->id }}</td>
    <td>{{ $show->nbspBeforeName($goodsCategory->name, $goodsCategory->level) }}</td>
    <td>{{ $goodsCategory->parent_id }}</td>
    <td>{{ $goodsCategory->level }}</td>
    <td  class="text-center">
      {!! $show->getImage($goodsCategory->image) !!}
    </td>
    <td  class="text-center">{!! $goodsCategory->font_icon !!}</td>
    <td>{{ $goodsCategory->path }}</td>
    <td>{{ $goodsCategory->order }}</td>
    {!! $show->isShown($goodsCategory->is_shown) !!}
    {!! $show->isRecommended($goodsCategory->is_recommended) !!}
    <td>{{ $showCouponRule->showCat($couponRules[$goodsCategory->id]) }}</td>
    <td>{{ $showCouponRule->showPageSize($couponRules[$goodsCategory->id]) }}</td>
    <td>{{ $showCouponRule->showQ($couponRules[$goodsCategory->id]) }}</td>
    <td  class="text-left">
      <a href="{{ route('goodsCategorys.edit', $goodsCategory->id) }}" title="编辑"><i class="fa fa-edit"></i></a> |
      <a href0="{{ route('goodsCategorys.destroy', $goodsCategory->id) }}" title="删除" onclick="destroyGoodsCategory({{ $goodsCategory->id }})"><i class="fa fa-close text-danger"></i></a> |
      <a href="{{ route('goodsCategorys.show', $goodsCategory->id) }}" title="商品分类详情"><i class="fa fa-info-circle text-info"></i></a>
      <hr style="margin-top:3px; margin-bottom:3px;" />
      {!! $show->couponRuleAction($couponRules[$goodsCategory->id], $goodsCategory->id) !!}
    </td>
</tr>
<div style="display: none;">
  <form id="destroy{{ $goodsCategory->id }}" action="{{ route('goodsCategorys.destroy', $goodsCategory->id) }}" method="post">
    <input type="hidden" name="goods_category_id" value="{{ $goodsCategory->id }}">
    {{ csrf_field() }}
    {{ method_field('DELETE') }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">登陆</button>
  </form>
</div>
@endforeach

resources/views/admin/goodsCategory/create.blade.php
@extends('admin.layouts.form.index')

@section('title', $title)
@section('headcss')

@stop
@section('content')
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
      <div class="ibox float-e-margins">
          @include('admin.layouts.form._errors')
          @include('admin.layouts.form._tips')
          <div class="ibox-title">
              <h5>增加商品分类</h5>
          </div>
          <div class="ibox-content" style="display: block;">
              <form class="form-horizontal" method="post" action="{{ route('goodsCategorys.store') }}" target="_self" enctype="multipart/form-data">
                  <div class="col-md-12">
                      <div class="form-group">
                          <label class="col-sm-3 control-label">分类名称：</label>
                          <div class="col-sm-9">
                              <input type="text" name="name" value="{{ old('name') }}" required class="form-control" placeholder="请输入分类的名称">
                          </div>
                      </div>
                      @inject('Options', 'App\Presenters\OptionPresenter')
                      <div class="form-group">
                          <label class="col-sm-3 control-label">所属栏目：</label>
                          <div class="col-sm-9">
                              <select class="form-control" name="parent_id">
                                <option value="0">顶级分类</option>
                                {!! $Options->goodsCategoryOptions($options) !!}
                              </select>
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">排列顺序：</label>
                          <div class="col-sm-9">
                              <input type="number" name="order" required class="form-control" value="0" min="0" max="99" step="1" placeholder="请输入排序">
                              <span class="help-block m-b-none">数字越大排序余额靠前，最大值99</span>

                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">图片：</label>
                          <div class="col-sm-9">
                              <input type="file" required name="image" class="form-control">
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">字体图标：</label>
                          <div class="col-sm-9">
                              <input type="text" name="font_icon" value="{{ old('font_icon') }}" class="form-control" placeholder="请输入字体图标的完整标签">
                              <span class="help-block m-b-none">格式：&lt;i class="font-icon font-icon-home"&gt;&lt;/i&gt;</span>

                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">是否展示：</label>
                          <div class="col-sm-9">
                              <label class="radio-inline">
                                  <input type="radio" checked="" value="1" id="optionsRadios1" name="is_shown">是</label>
                              <label class="radio-inline">
                                  <input type="radio" value="0" id="optionsRadios2" name="is_shown">否</label>
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label" for="-NaN">是否推荐：</label>
                          <div class="col-sm-9">
                              <label class="radio-inline" for="-NaN">
                                  <input type="radio"  value="1" id="-NaN" name="is_recommended">是</label>
                              <label class="radio-inline" for="-NaN">
                                  <input type="radio" checked value="0" id="-NaN" name="is_recommended">否</label>
                          </div>
                      </div>
                  </div>
                  {{ csrf_field() }}
                  <div class="form-group">
                      <div class="col-sm-offset-3 col-sm-8">
                          <button class="btn btn-sm btn-primary" type="submit">提 交</button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
  </div>
</div>
@stop
@section('footJs')

@stop

resources/views/admin/goodsCategory/edit.blade.php
@extends('admin.layouts.form.index')

@section('title', $title)
@section('headcss')

@stop
@section('content')
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
      <div class="ibox float-e-margins">
          @include('admin.layouts.form._errors')
          @include('admin.layouts.form._tips')
          <div class="ibox-title">
              <h5>修改商品分类</h5>
              <div class="ibox-tools">
                  <a href="{{ route('goodsCategorys.index') }}">
                      商品分类列表
                  </a>
              </div>
          </div>
          <div class="ibox-content" style="display: block;">
              <form class="form-horizontal" method="post" action="{{ route('goodsCategorys.update', $goodsCategory->id) }}" target="_self" enctype="multipart/form-data">
                  <div class="col-md-12">
                      <div class="form-group">
                          <label class="col-sm-3 control-label">分类名称：</label>
                          <div class="col-sm-9">
                              <input type="text" name="name" value="{{ $goodsCategory->name }}" required class="form-control" placeholder="请输入分类的名称">
                          </div>
                      </div>
                      @inject('show', 'App\Presenters\GoodsCategoryPresenter')
                      @inject('Options', 'App\Presenters\OptionPresenter')
                      <div class="form-group">
                          <label class="col-sm-3 control-label">所属栏目：</label>
                          <div class="col-sm-9">
                              <select class="form-control" name="parent_id">
                                <option value="0">顶级分类</option>
                                {!! $Options->goodsCategoryOptions($options, $goodsCategory->parent_id, $goodsCategory->id) !!}
                              </select>
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">排列顺序：</label>
                          <div class="col-sm-9">
                              <input type="number" name="order" required class="form-control" value="{{ $goodsCategory->order }}" min="0" max="99" step="1" placeholder="请输入排序">
                              <span class="help-block m-b-none">数字越大排序余额靠前，最大值99</span>

                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">图片：</label>
                          <div class="col-sm-9">
                              {!! $show->getImage($goodsCategory->image) !!}
                              <input type="file" name="image" class="form-control">
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">字体图标：</label>
                          <div class="col-sm-9">
                              <input type="text" name="font_icon" value="{{ $goodsCategory->font_icon }}" class="form-control" placeholder="请输入字体图标的完整标签">
                              <span class="help-block m-b-none">格式：&lt;i class="font-icon font-icon-home"&gt;&lt;/i&gt;</span>

                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label">是否展示：</label>
                          <div class="col-sm-9">
                              <label class="radio-inline">
                                  <input type="radio" {{ $show->isChecked(1, $goodsCategory->is_shown) }} value="1" id="optionsRadios1" name="is_shown">是</label>
                              <label class="radio-inline">
                                  <input type="radio" {{ $show->isChecked(0, $goodsCategory->is_shown) }} value="0" id="optionsRadios2" name="is_shown">否</label>
                          </div>
                      </div>
                      <div class="form-group">
                          <label class="col-sm-3 control-label" for="-NaN">是否推荐：</label>
                          <div class="col-sm-9">
                              <label class="radio-inline" for="-NaN">
                                  <input type="radio" {{ $show->isChecked(1, $goodsCategory->is_recommended) }}  value="1" id="-NaN" name="is_recommended">是</label>
                              <label class="radio-inline" for="-NaN">
                                  <input type="radio" {{ $show->isChecked(0, $goodsCategory->is_recommended) }} value="0" id="-NaN" name="is_recommended">否</label>
                          </div>
                      </div>
                  </div>
                  {{ csrf_field() }}
                  {{ method_field('PATCH') }}
                  <div class="form-group">
                      <div class="col-sm-offset-3 col-sm-8">
                          <button class="btn btn-sm btn-primary" type="submit">提 交</button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
  </div>
</div>
@stop
@section('footJs')

@stop

resources/views/admin/goodsCategory/index.blade.php
@extends('admin.layouts.table.index')

@section('title', $title)
@section('headcss')

@stop
@section('content')
<div class="row">
  <div class="col-sm-12">
    @include('admin.layouts.form._errors')
    @include('admin.layouts.form._tips')
      <div class="ibox float-e-margins">
          <div class="ibox-title">
              <h5>商品分类列表</h5>
          </div>
          <div class="ibox-content">
              <table class="table table-hover">
                  <thead>
                      <tr>
                          <th>id</th>
                          <th>名称</th>
                          <th>父ID</th>
                          <th>等级</th>
                          <th class="text-center">图片</th>
                          <th class="text-center">图标</th>
                          <th>path字段</th>
                          <th>排序</th>
                          <th  class="text-center">显示？</th>
                          <th  class="text-center">推荐？</th>
                          <th  class="text-center">类目id</th>
                          <th  class="text-center">页大小</th>
                          <th  class="text-center">查询词</th>
                          <th  class="text-center">编辑</th>
                      </tr>
                  </thead>
                  <tbody>
                    @include('admin.goodsCategory._info')
                  </tbody>
              </table>
              <div class="row text-center">
                {{ $goodsCategories->render() }}
              </div>
          </div>
      </div>
  </div>
</div>
@stop
@section('footJs')
<script type="text/javascript">
  function destroyGoodsCategory($goodsCategoryId)
  {
    r=confirm("确实删除信息吗？");
    if (r == true) {
      idStr = 'destroy'+$goodsCategoryId;
      targetForm = document.getElementById(idStr);
      targetForm.submit();
    }
  }
</script>
@stop